# Student Information System: accept and display student details.
name = input("Enter Student Name   : ")
roll = input("Enter Roll Number    : ")
branch = input("Enter Branch         : ")
semester = input("Enter Semester       : ")
college = input("Enter College Name   : ")
mobile = input("Enter Mobile Number  : ")
email = input("Enter Email ID       : ")
cgpa = float(input("Enter CGPA           : "))

print("\n" + "=" * 40)
print(f"{'STUDENT INFORMATION SYSTEM':^40}")
print("=" * 40)
print(f"{'Name':<15}: {name}")
print(f"{'Roll Number':<15}: {roll}")
print(f"{'Branch':<15}: {branch}")
print(f"{'Semester':<15}: {semester}")
print(f"{'College':<15}: {college}")
print(f"{'Mobile No.':<15}: {mobile}")
print(f"{'Email ID':<15}: {email}")
print(f"{'CGPA':<15}: {cgpa:.2f}")
print("=" * 40)
